-- GPA URL for 1st semester to 8th semester column
ALTER TABLE IF EXISTS students ADD COLUMN IF NOT EXISTS semester1_gpa_url VARCHAR(255);
ALTER TABLE IF EXISTS students ADD COLUMN IF NOT EXISTS semester2_gpa_url VARCHAR(255);
ALTER TABLE IF EXISTS students ADD COLUMN IF NOT EXISTS semester3_gpa_url VARCHAR(255);
ALTER TABLE IF EXISTS students ADD COLUMN IF NOT EXISTS semester4_gpa_url VARCHAR(255);
ALTER TABLE IF EXISTS students ADD COLUMN IF NOT EXISTS semester5_gpa_url VARCHAR(255);
ALTER TABLE IF EXISTS students ADD COLUMN IF NOT EXISTS semester6_gpa_url VARCHAR(255);
ALTER TABLE IF EXISTS students ADD COLUMN IF NOT EXISTS semester7_gpa_url VARCHAR(255);
ALTER TABLE IF EXISTS students ADD COLUMN IF NOT EXISTS semester8_gpa_url VARCHAR(255);