CREATE TABLE IF NOT EXISTS certifications
(
    id          bigserial PRIMARY KEY,
    title       varchar(150) NOT NULL,
    description varchar(250) NOT NULL,
    url         varchar(250) NOT NULL, -- Will be generated by backend
    provider    varchar(50)  NOT NULL, -- AWS, Microsoft, Google, etc.
    cert_id     varchar(100) NOT NULL DEFAULT '',
    created_at  timestamp    NOT NULL DEFAULT NOW(),
    updated_at  timestamp    NOT NULL DEFAULT NOW()
);