// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: internal/proto/hr/hr.proto

package hrPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone   string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Company string `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	Id      int64  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Hr) Reset() {
	*x = Hr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hr) ProtoMessage() {}

func (x *Hr) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hr.ProtoReflect.Descriptor instead.
func (*Hr) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{0}
}

func (x *Hr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hr) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Hr) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Hr) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Hr) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateHrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hr *Hr `protobuf:"bytes,1,opt,name=hr,proto3" json:"hr,omitempty"`
}

func (x *CreateHrRequest) Reset() {
	*x = CreateHrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHrRequest) ProtoMessage() {}

func (x *CreateHrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHrRequest.ProtoReflect.Descriptor instead.
func (*CreateHrRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHrRequest) GetHr() *Hr {
	if x != nil {
		return x.Hr
	}
	return nil
}

type CreateHrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateHrResponse) Reset() {
	*x = CreateHrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHrResponse) ProtoMessage() {}

func (x *CreateHrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHrResponse.ProtoReflect.Descriptor instead.
func (*CreateHrResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHrResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateHrResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteHrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteHrRequest) Reset() {
	*x = DeleteHrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHrRequest) ProtoMessage() {}

func (x *DeleteHrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHrRequest.ProtoReflect.Descriptor instead.
func (*DeleteHrRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteHrRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteHrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteHrResponse) Reset() {
	*x = DeleteHrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHrResponse) ProtoMessage() {}

func (x *DeleteHrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHrResponse.ProtoReflect.Descriptor instead.
func (*DeleteHrResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteHrResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetHrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetHrRequest) Reset() {
	*x = GetHrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHrRequest) ProtoMessage() {}

func (x *GetHrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHrRequest.ProtoReflect.Descriptor instead.
func (*GetHrRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{5}
}

func (x *GetHrRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hr []*Hr `protobuf:"bytes,1,rep,name=hr,proto3" json:"hr,omitempty"`
}

func (x *GetHrResponse) Reset() {
	*x = GetHrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHrResponse) ProtoMessage() {}

func (x *GetHrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHrResponse.ProtoReflect.Descriptor instead.
func (*GetHrResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{6}
}

func (x *GetHrResponse) GetHr() []*Hr {
	if x != nil {
		return x.Hr
	}
	return nil
}

// The hiring request, will contain the detail of hiring round.
// Role for which hiring is being done.
// Department for which hiring is being done.
// Hiring manager for the hiring.
// Required skills for the role.
// Required experience for the role.
// Required education for the role. cgpa, degree, college, year of passing.
// Required certifications for the role.
// Required location for the role.
type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role           string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Department     string `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Skills         string `protobuf:"bytes,4,opt,name=skills,proto3" json:"skills,omitempty"`
	Experience     string `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`
	RequiredCgpa   string `protobuf:"bytes,6,opt,name=required_cgpa,json=requiredCgpa,proto3" json:"required_cgpa,omitempty"`
	Description    string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Location       string `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Certifications string `protobuf:"bytes,9,opt,name=certifications,proto3" json:"certifications,omitempty"`
	Title          string `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Company        string `protobuf:"bytes,11,opt,name=company,proto3" json:"company,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{7}
}

func (x *Job) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Job) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Job) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *Job) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *Job) GetRequiredCgpa() string {
	if x != nil {
		return x.RequiredCgpa
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Job) GetCertifications() string {
	if x != nil {
		return x.Certifications
	}
	return ""
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

type CreateHiringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HrId int64 `protobuf:"varint,1,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"` // id of hiring manager.
	Job  *Job  `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *CreateHiringRequest) Reset() {
	*x = CreateHiringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHiringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHiringRequest) ProtoMessage() {}

func (x *CreateHiringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHiringRequest.ProtoReflect.Descriptor instead.
func (*CreateHiringRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{8}
}

func (x *CreateHiringRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *CreateHiringRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type CreateHiringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateHiringResponse) Reset() {
	*x = CreateHiringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHiringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHiringResponse) ProtoMessage() {}

func (x *CreateHiringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHiringResponse.ProtoReflect.Descriptor instead.
func (*CreateHiringResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{9}
}

func (x *CreateHiringResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteHiringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteHiringRequest) Reset() {
	*x = DeleteHiringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHiringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHiringRequest) ProtoMessage() {}

func (x *DeleteHiringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHiringRequest.ProtoReflect.Descriptor instead.
func (*DeleteHiringRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteHiringRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteHiringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteHiringResponse) Reset() {
	*x = DeleteHiringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHiringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHiringResponse) ProtoMessage() {}

func (x *DeleteHiringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHiringResponse.ProtoReflect.Descriptor instead.
func (*DeleteHiringResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteHiringResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{12}
}

func (x *GetJobRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetJobRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{13}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type JobSearchQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company  string `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Skills   string `protobuf:"bytes,4,opt,name=skills,proto3" json:"skills,omitempty"`
}

func (x *JobSearchQuery) Reset() {
	*x = JobSearchQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSearchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSearchQuery) ProtoMessage() {}

func (x *JobSearchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSearchQuery.ProtoReflect.Descriptor instead.
func (*JobSearchQuery) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{14}
}

func (x *JobSearchQuery) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobSearchQuery) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *JobSearchQuery) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobSearchQuery) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

// If none is provided, then all the jobs will be returned.
type GetAllJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *JobSearchQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *GetAllJobsRequest) Reset() {
	*x = GetAllJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllJobsRequest) ProtoMessage() {}

func (x *GetAllJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllJobsRequest.ProtoReflect.Descriptor instead.
func (*GetAllJobsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllJobsRequest) GetQuery() *JobSearchQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type GetAllJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jobs []*Job `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (x *GetAllJobsResponse) Reset() {
	*x = GetAllJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllJobsResponse) ProtoMessage() {}

func (x *GetAllJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllJobsResponse.ProtoReflect.Descriptor instead.
func (*GetAllJobsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_internal_proto_hr_hr_proto protoreflect.FileDescriptor

var file_internal_proto_hr_hr_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x72, 0x2f, 0x68, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x68, 0x72,
	0x22, 0x6e, 0x0a, 0x02, 0x68, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x29, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x68, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x68, 0x72, 0x2e, 0x68, 0x72, 0x52, 0x02, 0x68, 0x72, 0x22, 0x3c, 0x0a, 0x10, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0f, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x48, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x10,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x1e, 0x0a, 0x0c, 0x67, 0x65,
	0x74, 0x48, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x0d, 0x67, 0x65,
	0x74, 0x48, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x02, 0x68,
	0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x68, 0x72, 0x2e, 0x68, 0x72, 0x52,
	0x02, 0x68, 0x72, 0x22, 0xbc, 0x02, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x5f, 0x63, 0x67, 0x70, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x43, 0x67, 0x70, 0x61, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x22, 0x45, 0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x68, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x68, 0x72, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x68, 0x72,
	0x2e, 0x6a, 0x6f, 0x62, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x22, 0x30, 0x0a, 0x14, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x2b, 0x0a, 0x0e, 0x67,
	0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x03, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x68, 0x72, 0x2e,
	0x6a, 0x6f, 0x62, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x22, 0x74, 0x0a, 0x0e, 0x6a, 0x6f, 0x62, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x22, 0x3d,
	0x0a, 0x11, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x72, 0x2e, 0x6a, 0x6f, 0x62, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x31, 0x0a,
	0x12, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x68, 0x72, 0x2e, 0x6a, 0x6f, 0x62, 0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73,
	0x32, 0xa5, 0x03, 0x0a, 0x09, 0x68, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35,
	0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x72, 0x12, 0x13, 0x2e, 0x68, 0x72, 0x2e,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x68, 0x72, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48,
	0x72, 0x12, 0x13, 0x2e, 0x68, 0x72, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x68, 0x72, 0x2e, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x48, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05,
	0x47, 0x65, 0x74, 0x48, 0x72, 0x12, 0x10, 0x2e, 0x68, 0x72, 0x2e, 0x67, 0x65, 0x74, 0x48, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x68, 0x72, 0x2e, 0x67, 0x65, 0x74,
	0x48, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x2e, 0x68,
	0x72, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x68, 0x72, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x17, 0x2e, 0x68, 0x72, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x69, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x68, 0x72, 0x2e,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62,
	0x12, 0x11, 0x2e, 0x68, 0x72, 0x2e, 0x67, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x68, 0x72, 0x2e, 0x67, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x15, 0x2e, 0x68, 0x72, 0x2e, 0x67, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x68, 0x72, 0x2e, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x68, 0x72, 0x2f, 0x68,
	0x72, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_hr_hr_proto_rawDescOnce sync.Once
	file_internal_proto_hr_hr_proto_rawDescData = file_internal_proto_hr_hr_proto_rawDesc
)

func file_internal_proto_hr_hr_proto_rawDescGZIP() []byte {
	file_internal_proto_hr_hr_proto_rawDescOnce.Do(func() {
		file_internal_proto_hr_hr_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_hr_hr_proto_rawDescData)
	})
	return file_internal_proto_hr_hr_proto_rawDescData
}

var file_internal_proto_hr_hr_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_proto_hr_hr_proto_goTypes = []interface{}{
	(*Hr)(nil),                   // 0: hr.hr
	(*CreateHrRequest)(nil),      // 1: hr.createHrRequest
	(*CreateHrResponse)(nil),     // 2: hr.createHrResponse
	(*DeleteHrRequest)(nil),      // 3: hr.deleteHrRequest
	(*DeleteHrResponse)(nil),     // 4: hr.deleteHrResponse
	(*GetHrRequest)(nil),         // 5: hr.getHrRequest
	(*GetHrResponse)(nil),        // 6: hr.getHrResponse
	(*Job)(nil),                  // 7: hr.job
	(*CreateHiringRequest)(nil),  // 8: hr.createHiringRequest
	(*CreateHiringResponse)(nil), // 9: hr.createHiringResponse
	(*DeleteHiringRequest)(nil),  // 10: hr.deleteHiringRequest
	(*DeleteHiringResponse)(nil), // 11: hr.deleteHiringResponse
	(*GetJobRequest)(nil),        // 12: hr.getJobRequest
	(*GetJobResponse)(nil),       // 13: hr.getJobResponse
	(*JobSearchQuery)(nil),       // 14: hr.jobSearchQuery
	(*GetAllJobsRequest)(nil),    // 15: hr.getAllJobsRequest
	(*GetAllJobsResponse)(nil),   // 16: hr.getAllJobsResponse
}
var file_internal_proto_hr_hr_proto_depIdxs = []int32{
	0,  // 0: hr.createHrRequest.hr:type_name -> hr.hr
	0,  // 1: hr.getHrResponse.hr:type_name -> hr.hr
	7,  // 2: hr.createHiringRequest.job:type_name -> hr.job
	7,  // 3: hr.getJobResponse.job:type_name -> hr.job
	14, // 4: hr.getAllJobsRequest.query:type_name -> hr.jobSearchQuery
	7,  // 5: hr.getAllJobsResponse.jobs:type_name -> hr.job
	1,  // 6: hr.hrService.CreateHr:input_type -> hr.createHrRequest
	3,  // 7: hr.hrService.DeleteHr:input_type -> hr.deleteHrRequest
	5,  // 8: hr.hrService.GetHr:input_type -> hr.getHrRequest
	8,  // 9: hr.hrService.CreateHiring:input_type -> hr.createHiringRequest
	10, // 10: hr.hrService.DeleteHiring:input_type -> hr.deleteHiringRequest
	12, // 11: hr.hrService.GetJob:input_type -> hr.getJobRequest
	15, // 12: hr.hrService.GetAllJobs:input_type -> hr.getAllJobsRequest
	2,  // 13: hr.hrService.CreateHr:output_type -> hr.createHrResponse
	4,  // 14: hr.hrService.DeleteHr:output_type -> hr.deleteHrResponse
	6,  // 15: hr.hrService.GetHr:output_type -> hr.getHrResponse
	9,  // 16: hr.hrService.CreateHiring:output_type -> hr.createHiringResponse
	11, // 17: hr.hrService.DeleteHiring:output_type -> hr.deleteHiringResponse
	13, // 18: hr.hrService.GetJob:output_type -> hr.getJobResponse
	16, // 19: hr.hrService.GetAllJobs:output_type -> hr.getAllJobsResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_proto_hr_hr_proto_init() }
func file_internal_proto_hr_hr_proto_init() {
	if File_internal_proto_hr_hr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_hr_hr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHiringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHiringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHiringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHiringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSearchQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_hr_hr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_hr_hr_proto_goTypes,
		DependencyIndexes: file_internal_proto_hr_hr_proto_depIdxs,
		MessageInfos:      file_internal_proto_hr_hr_proto_msgTypes,
	}.Build()
	File_internal_proto_hr_hr_proto = out.File
	file_internal_proto_hr_hr_proto_rawDesc = nil
	file_internal_proto_hr_hr_proto_goTypes = nil
	file_internal_proto_hr_hr_proto_depIdxs = nil
}
