// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: internal/proto/hr/hr.proto

package hrPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone   string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Company string `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	Id      int64  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Hr) Reset() {
	*x = Hr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hr) ProtoMessage() {}

func (x *Hr) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hr.ProtoReflect.Descriptor instead.
func (*Hr) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{0}
}

func (x *Hr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hr) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Hr) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Hr) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Hr) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetHrRequest) Reset() {
	*x = GetHrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHrRequest) ProtoMessage() {}

func (x *GetHrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHrRequest.ProtoReflect.Descriptor instead.
func (*GetHrRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{1}
}

func (x *GetHrRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetHrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hr *Hr `protobuf:"bytes,1,opt,name=hr,proto3" json:"hr,omitempty"`
}

func (x *GetHrResponse) Reset() {
	*x = GetHrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHrResponse) ProtoMessage() {}

func (x *GetHrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHrResponse.ProtoReflect.Descriptor instead.
func (*GetHrResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{2}
}

func (x *GetHrResponse) GetHr() *Hr {
	if x != nil {
		return x.Hr
	}
	return nil
}

// The hiring request, will contain the detail of hiring round.
// Role for which hiring is being done.
// Department for which hiring is being done.
// Hiring manager for the hiring.
// Required skills for the role.
// Required experience for the role.
// Required education for the role. cgpa, degree, college, year of passing.
// Required certifications for the role.
// Required location for the role.
type CreateHiringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HrId           int64  `protobuf:"varint,1,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"` // id of hiring manager.
	Role           string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Department     string `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Skills         string `protobuf:"bytes,4,opt,name=skills,proto3" json:"skills,omitempty"`
	Experience     string `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`
	RequiredCgpa   string `protobuf:"bytes,6,opt,name=required_cgpa,json=requiredCgpa,proto3" json:"required_cgpa,omitempty"`
	Description    string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Location       string `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Certifications string `protobuf:"bytes,9,opt,name=certifications,proto3" json:"certifications,omitempty"`
	Title          string `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *CreateHiringRequest) Reset() {
	*x = CreateHiringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHiringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHiringRequest) ProtoMessage() {}

func (x *CreateHiringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHiringRequest.ProtoReflect.Descriptor instead.
func (*CreateHiringRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHiringRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *CreateHiringRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateHiringRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateHiringRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *CreateHiringRequest) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *CreateHiringRequest) GetRequiredCgpa() string {
	if x != nil {
		return x.RequiredCgpa
	}
	return ""
}

func (x *CreateHiringRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateHiringRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateHiringRequest) GetCertifications() string {
	if x != nil {
		return x.Certifications
	}
	return ""
}

func (x *CreateHiringRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateHiringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateHiringResponse) Reset() {
	*x = CreateHiringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hr_hr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHiringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHiringResponse) ProtoMessage() {}

func (x *CreateHiringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hr_hr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHiringResponse.ProtoReflect.Descriptor instead.
func (*CreateHiringResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hr_hr_proto_rawDescGZIP(), []int{4}
}

func (x *CreateHiringResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_proto_hr_hr_proto protoreflect.FileDescriptor

var file_internal_proto_hr_hr_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x72, 0x2f, 0x68, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x68, 0x72,
	0x22, 0x6e, 0x0a, 0x02, 0x68, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x22, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x48, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x48, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x02, 0x68, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x68, 0x72, 0x2e, 0x68, 0x72, 0x52, 0x02, 0x68, 0x72, 0x22, 0xb7, 0x02,
	0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x68, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x68, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x5f, 0x63, 0x67, 0x70, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x43, 0x67, 0x70, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x80, 0x01, 0x0a, 0x09, 0x68, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x67, 0x65, 0x74, 0x48, 0x72,
	0x12, 0x10, 0x2e, 0x68, 0x72, 0x2e, 0x67, 0x65, 0x74, 0x48, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x68, 0x72, 0x2e, 0x67, 0x65, 0x74, 0x48, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x2e, 0x68, 0x72, 0x2e, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x68, 0x72, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07,
	0x68, 0x72, 0x2f, 0x68, 0x72, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_hr_hr_proto_rawDescOnce sync.Once
	file_internal_proto_hr_hr_proto_rawDescData = file_internal_proto_hr_hr_proto_rawDesc
)

func file_internal_proto_hr_hr_proto_rawDescGZIP() []byte {
	file_internal_proto_hr_hr_proto_rawDescOnce.Do(func() {
		file_internal_proto_hr_hr_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_hr_hr_proto_rawDescData)
	})
	return file_internal_proto_hr_hr_proto_rawDescData
}

var file_internal_proto_hr_hr_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_hr_hr_proto_goTypes = []interface{}{
	(*Hr)(nil),                   // 0: hr.hr
	(*GetHrRequest)(nil),         // 1: hr.getHrRequest
	(*GetHrResponse)(nil),        // 2: hr.getHrResponse
	(*CreateHiringRequest)(nil),  // 3: hr.createHiringRequest
	(*CreateHiringResponse)(nil), // 4: hr.createHiringResponse
}
var file_internal_proto_hr_hr_proto_depIdxs = []int32{
	0, // 0: hr.getHrResponse.hr:type_name -> hr.hr
	1, // 1: hr.hrService.getHr:input_type -> hr.getHrRequest
	3, // 2: hr.hrService.createHiring:input_type -> hr.createHiringRequest
	2, // 3: hr.hrService.getHr:output_type -> hr.getHrResponse
	4, // 4: hr.hrService.createHiring:output_type -> hr.createHiringResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_hr_hr_proto_init() }
func file_internal_proto_hr_hr_proto_init() {
	if File_internal_proto_hr_hr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_hr_hr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHiringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hr_hr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHiringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_hr_hr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_hr_hr_proto_goTypes,
		DependencyIndexes: file_internal_proto_hr_hr_proto_depIdxs,
		MessageInfos:      file_internal_proto_hr_hr_proto_msgTypes,
	}.Build()
	File_internal_proto_hr_hr_proto = out.File
	file_internal_proto_hr_hr_proto_rawDesc = nil
	file_internal_proto_hr_hr_proto_goTypes = nil
	file_internal_proto_hr_hr_proto_depIdxs = nil
}
