// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: internal/proto/application/application.proto

package jobApplicationPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobApplication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentId int64 `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	JobId     int64 `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *JobApplication) Reset() {
	*x = JobApplication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_application_application_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplication) ProtoMessage() {}

func (x *JobApplication) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_application_application_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplication.ProtoReflect.Descriptor instead.
func (*JobApplication) Descriptor() ([]byte, []int) {
	return file_internal_proto_application_application_proto_rawDescGZIP(), []int{0}
}

func (x *JobApplication) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *JobApplication) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type JobApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Application *JobApplication `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
}

func (x *JobApplicationRequest) Reset() {
	*x = JobApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_application_application_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplicationRequest) ProtoMessage() {}

func (x *JobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_application_application_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplicationRequest.ProtoReflect.Descriptor instead.
func (*JobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_application_application_proto_rawDescGZIP(), []int{1}
}

func (x *JobApplicationRequest) GetApplication() *JobApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

type JobApplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *JobApplicationResponse) Reset() {
	*x = JobApplicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_application_application_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplicationResponse) ProtoMessage() {}

func (x *JobApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_application_application_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplicationResponse.ProtoReflect.Descriptor instead.
func (*JobApplicationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_application_application_proto_rawDescGZIP(), []int{2}
}

func (x *JobApplicationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type JobApplicationStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *JobApplicationStatusRequest) Reset() {
	*x = JobApplicationStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_application_application_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplicationStatusRequest) ProtoMessage() {}

func (x *JobApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_application_application_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*JobApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_application_application_proto_rawDescGZIP(), []int{3}
}

func (x *JobApplicationStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type JobApplicationStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *JobApplicationStatusResponse) Reset() {
	*x = JobApplicationStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_application_application_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplicationStatusResponse) ProtoMessage() {}

func (x *JobApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_application_application_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*JobApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_application_application_proto_rawDescGZIP(), []int{4}
}

func (x *JobApplicationStatusResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type AllJobApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AllJobApplicationRequest) Reset() {
	*x = AllJobApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_application_application_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllJobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllJobApplicationRequest) ProtoMessage() {}

func (x *AllJobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_application_application_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllJobApplicationRequest.ProtoReflect.Descriptor instead.
func (*AllJobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_application_application_proto_rawDescGZIP(), []int{5}
}

func (x *AllJobApplicationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AllJobApplicationStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyName string `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Role        string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Status      bool   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	AppId       int64  `protobuf:"varint,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *AllJobApplicationStatus) Reset() {
	*x = AllJobApplicationStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_application_application_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllJobApplicationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllJobApplicationStatus) ProtoMessage() {}

func (x *AllJobApplicationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_application_application_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllJobApplicationStatus.ProtoReflect.Descriptor instead.
func (*AllJobApplicationStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_application_application_proto_rawDescGZIP(), []int{6}
}

func (x *AllJobApplicationStatus) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AllJobApplicationStatus) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *AllJobApplicationStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AllJobApplicationStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AllJobApplicationStatus) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type AllJobApplicationStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Application []*AllJobApplicationStatus `protobuf:"bytes,1,rep,name=application,proto3" json:"application,omitempty"`
}

func (x *AllJobApplicationStatusResponse) Reset() {
	*x = AllJobApplicationStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_application_application_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllJobApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllJobApplicationStatusResponse) ProtoMessage() {}

func (x *AllJobApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_application_application_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllJobApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*AllJobApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_application_application_proto_rawDescGZIP(), []int{7}
}

func (x *AllJobApplicationStatusResponse) GetApplication() []*AllJobApplicationStatus {
	if x != nil {
		return x.Application
	}
	return nil
}

var File_internal_proto_application_application_proto protoreflect.FileDescriptor

var file_internal_proto_application_application_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x46, 0x0a, 0x0e, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x15, 0x4a, 0x6f, 0x62, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x41, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x16, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2d, 0x0a, 0x1b, 0x4a, 0x6f, 0x62, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x1c, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a,
	0x0a, 0x18, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x17, 0x41,
	0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x1f,
	0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4a, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xf6, 0x02, 0x0a, 0x15,
	0x6a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x4a, 0x6f, 0x62, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x6a, 0x6f, 0x62,
	0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x78, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7b, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x30, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x6a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_application_application_proto_rawDescOnce sync.Once
	file_internal_proto_application_application_proto_rawDescData = file_internal_proto_application_application_proto_rawDesc
)

func file_internal_proto_application_application_proto_rawDescGZIP() []byte {
	file_internal_proto_application_application_proto_rawDescOnce.Do(func() {
		file_internal_proto_application_application_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_application_application_proto_rawDescData)
	})
	return file_internal_proto_application_application_proto_rawDescData
}

var file_internal_proto_application_application_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_application_application_proto_goTypes = []interface{}{
	(*JobApplication)(nil),                  // 0: job_application.JobApplication
	(*JobApplicationRequest)(nil),           // 1: job_application.JobApplicationRequest
	(*JobApplicationResponse)(nil),          // 2: job_application.JobApplicationResponse
	(*JobApplicationStatusRequest)(nil),     // 3: job_application.JobApplicationStatusRequest
	(*JobApplicationStatusResponse)(nil),    // 4: job_application.JobApplicationStatusResponse
	(*AllJobApplicationRequest)(nil),        // 5: job_application.AllJobApplicationRequest
	(*AllJobApplicationStatus)(nil),         // 6: job_application.AllJobApplicationStatus
	(*AllJobApplicationStatusResponse)(nil), // 7: job_application.AllJobApplicationStatusResponse
}
var file_internal_proto_application_application_proto_depIdxs = []int32{
	0, // 0: job_application.JobApplicationRequest.application:type_name -> job_application.JobApplication
	6, // 1: job_application.AllJobApplicationStatusResponse.application:type_name -> job_application.AllJobApplicationStatus
	1, // 2: job_application.jobApplicationService.AddJobApplication:input_type -> job_application.JobApplicationRequest
	3, // 3: job_application.jobApplicationService.GetJobApplicationStatus:input_type -> job_application.JobApplicationStatusRequest
	5, // 4: job_application.jobApplicationService.GetAllJobApplicationStatus:input_type -> job_application.AllJobApplicationRequest
	2, // 5: job_application.jobApplicationService.AddJobApplication:output_type -> job_application.JobApplicationResponse
	4, // 6: job_application.jobApplicationService.GetJobApplicationStatus:output_type -> job_application.JobApplicationStatusResponse
	7, // 7: job_application.jobApplicationService.GetAllJobApplicationStatus:output_type -> job_application.AllJobApplicationStatusResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_application_application_proto_init() }
func file_internal_proto_application_application_proto_init() {
	if File_internal_proto_application_application_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_application_application_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobApplication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_application_application_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_application_application_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobApplicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_application_application_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobApplicationStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_application_application_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobApplicationStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_application_application_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllJobApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_application_application_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllJobApplicationStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_application_application_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllJobApplicationStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_application_application_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_application_application_proto_goTypes,
		DependencyIndexes: file_internal_proto_application_application_proto_depIdxs,
		MessageInfos:      file_internal_proto_application_application_proto_msgTypes,
	}.Build()
	File_internal_proto_application_application_proto = out.File
	file_internal_proto_application_application_proto_rawDesc = nil
	file_internal_proto_application_application_proto_goTypes = nil
	file_internal_proto_application_application_proto_depIdxs = nil
}
