// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: internal/proto/internship/internship.proto

package internshipPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternshipFields struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location    string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Company     string                 `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	StartDate   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status      string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	MentorName  string                 `protobuf:"bytes,10,opt,name=mentor_name,json=mentorName,proto3" json:"mentor_name,omitempty"`
}

func (x *InternshipFields) Reset() {
	*x = InternshipFields{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternshipFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternshipFields) ProtoMessage() {}

func (x *InternshipFields) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternshipFields.ProtoReflect.Descriptor instead.
func (*InternshipFields) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{0}
}

func (x *InternshipFields) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InternshipFields) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InternshipFields) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InternshipFields) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *InternshipFields) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *InternshipFields) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *InternshipFields) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *InternshipFields) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InternshipFields) GetMentorName() string {
	if x != nil {
		return x.MentorName
	}
	return ""
}

type AddInternshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64             `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Internship *InternshipFields `protobuf:"bytes,2,opt,name=internship,proto3" json:"internship,omitempty"`
}

func (x *AddInternshipRequest) Reset() {
	*x = AddInternshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddInternshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInternshipRequest) ProtoMessage() {}

func (x *AddInternshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInternshipRequest.ProtoReflect.Descriptor instead.
func (*AddInternshipRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{1}
}

func (x *AddInternshipRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddInternshipRequest) GetInternship() *InternshipFields {
	if x != nil {
		return x.Internship
	}
	return nil
}

type AddInternshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddInternshipResponse) Reset() {
	*x = AddInternshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddInternshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInternshipResponse) ProtoMessage() {}

func (x *AddInternshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInternshipResponse.ProtoReflect.Descriptor instead.
func (*AddInternshipResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{2}
}

func (x *AddInternshipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetInternshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	InternshipId int64 `protobuf:"varint,2,opt,name=internshipId,proto3" json:"internshipId,omitempty"`
}

func (x *GetInternshipRequest) Reset() {
	*x = GetInternshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInternshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInternshipRequest) ProtoMessage() {}

func (x *GetInternshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInternshipRequest.ProtoReflect.Descriptor instead.
func (*GetInternshipRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{3}
}

func (x *GetInternshipRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetInternshipRequest) GetInternshipId() int64 {
	if x != nil {
		return x.InternshipId
	}
	return 0
}

type GetInternshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Internship *InternshipFields `protobuf:"bytes,1,opt,name=internship,proto3" json:"internship,omitempty"`
}

func (x *GetInternshipResponse) Reset() {
	*x = GetInternshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInternshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInternshipResponse) ProtoMessage() {}

func (x *GetInternshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInternshipResponse.ProtoReflect.Descriptor instead.
func (*GetInternshipResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{4}
}

func (x *GetInternshipResponse) GetInternship() *InternshipFields {
	if x != nil {
		return x.Internship
	}
	return nil
}

type GetAllInternshipsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetAllInternshipsRequest) Reset() {
	*x = GetAllInternshipsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInternshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInternshipsRequest) ProtoMessage() {}

func (x *GetAllInternshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInternshipsRequest.ProtoReflect.Descriptor instead.
func (*GetAllInternshipsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllInternshipsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAllInternshipsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Internships []*InternshipFields `protobuf:"bytes,1,rep,name=internships,proto3" json:"internships,omitempty"`
}

func (x *GetAllInternshipsResponse) Reset() {
	*x = GetAllInternshipsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInternshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInternshipsResponse) ProtoMessage() {}

func (x *GetAllInternshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInternshipsResponse.ProtoReflect.Descriptor instead.
func (*GetAllInternshipsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllInternshipsResponse) GetInternships() []*InternshipFields {
	if x != nil {
		return x.Internships
	}
	return nil
}

type UpdateInternshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64             `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Internship *InternshipFields `protobuf:"bytes,2,opt,name=internship,proto3" json:"internship,omitempty"`
}

func (x *UpdateInternshipRequest) Reset() {
	*x = UpdateInternshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInternshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInternshipRequest) ProtoMessage() {}

func (x *UpdateInternshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInternshipRequest.ProtoReflect.Descriptor instead.
func (*UpdateInternshipRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateInternshipRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateInternshipRequest) GetInternship() *InternshipFields {
	if x != nil {
		return x.Internship
	}
	return nil
}

type UpdateInternshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateInternshipResponse) Reset() {
	*x = UpdateInternshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInternshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInternshipResponse) ProtoMessage() {}

func (x *UpdateInternshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInternshipResponse.ProtoReflect.Descriptor instead.
func (*UpdateInternshipResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateInternshipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteInternshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	InternshipId int64 `protobuf:"varint,2,opt,name=internshipId,proto3" json:"internshipId,omitempty"`
}

func (x *DeleteInternshipRequest) Reset() {
	*x = DeleteInternshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInternshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInternshipRequest) ProtoMessage() {}

func (x *DeleteInternshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInternshipRequest.ProtoReflect.Descriptor instead.
func (*DeleteInternshipRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInternshipRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteInternshipRequest) GetInternshipId() int64 {
	if x != nil {
		return x.InternshipId
	}
	return 0
}

type DeleteInternshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteInternshipResponse) Reset() {
	*x = DeleteInternshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_internship_internship_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInternshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInternshipResponse) ProtoMessage() {}

func (x *DeleteInternshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_internship_internship_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInternshipResponse.ProtoReflect.Descriptor instead.
func (*DeleteInternshipResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_internship_internship_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteInternshipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto_internship_internship_proto protoreflect.FileDescriptor

var file_internal_proto_internship_internship_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba, 0x02, 0x0a, 0x11, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6d, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x73, 0x68, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68,
	0x69, 0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x22, 0x31, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x52, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73,
	0x68, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69,
	0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x73, 0x68, 0x69, 0x70, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73,
	0x68, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68,
	0x69, 0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x22, 0x70, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0a, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x0a, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x22, 0x34, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x55,
	0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68,
	0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73,
	0x68, 0x69, 0x70, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xdf, 0x03, 0x0a, 0x11,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x54, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68,
	0x69, 0x70, 0x12, 0x20, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e,
	0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69,
	0x70, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x12, 0x20, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69,
	0x70, 0x73, 0x12, 0x24, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5d, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73,
	0x68, 0x69, 0x70, 0x12, 0x23, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68,
	0x69, 0x70, 0x12, 0x23, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x73, 0x68, 0x69, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a,
	0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_internship_internship_proto_rawDescOnce sync.Once
	file_internal_proto_internship_internship_proto_rawDescData = file_internal_proto_internship_internship_proto_rawDesc
)

func file_internal_proto_internship_internship_proto_rawDescGZIP() []byte {
	file_internal_proto_internship_internship_proto_rawDescOnce.Do(func() {
		file_internal_proto_internship_internship_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_internship_internship_proto_rawDescData)
	})
	return file_internal_proto_internship_internship_proto_rawDescData
}

var file_internal_proto_internship_internship_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_proto_internship_internship_proto_goTypes = []interface{}{
	(*InternshipFields)(nil),          // 0: internship.Internship_fields
	(*AddInternshipRequest)(nil),      // 1: internship.AddInternshipRequest
	(*AddInternshipResponse)(nil),     // 2: internship.AddInternshipResponse
	(*GetInternshipRequest)(nil),      // 3: internship.GetInternshipRequest
	(*GetInternshipResponse)(nil),     // 4: internship.GetInternshipResponse
	(*GetAllInternshipsRequest)(nil),  // 5: internship.GetAllInternshipsRequest
	(*GetAllInternshipsResponse)(nil), // 6: internship.GetAllInternshipsResponse
	(*UpdateInternshipRequest)(nil),   // 7: internship.UpdateInternshipRequest
	(*UpdateInternshipResponse)(nil),  // 8: internship.UpdateInternshipResponse
	(*DeleteInternshipRequest)(nil),   // 9: internship.DeleteInternshipRequest
	(*DeleteInternshipResponse)(nil),  // 10: internship.DeleteInternshipResponse
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_internal_proto_internship_internship_proto_depIdxs = []int32{
	11, // 0: internship.Internship_fields.start_date:type_name -> google.protobuf.Timestamp
	11, // 1: internship.Internship_fields.end_date:type_name -> google.protobuf.Timestamp
	0,  // 2: internship.AddInternshipRequest.internship:type_name -> internship.Internship_fields
	0,  // 3: internship.GetInternshipResponse.internship:type_name -> internship.Internship_fields
	0,  // 4: internship.GetAllInternshipsResponse.internships:type_name -> internship.Internship_fields
	0,  // 5: internship.UpdateInternshipRequest.internship:type_name -> internship.Internship_fields
	1,  // 6: internship.InternshipService.AddInternship:input_type -> internship.AddInternshipRequest
	3,  // 7: internship.InternshipService.GetInternship:input_type -> internship.GetInternshipRequest
	5,  // 8: internship.InternshipService.GetAllInternships:input_type -> internship.GetAllInternshipsRequest
	7,  // 9: internship.InternshipService.UpdateInternship:input_type -> internship.UpdateInternshipRequest
	9,  // 10: internship.InternshipService.DeleteInternship:input_type -> internship.DeleteInternshipRequest
	2,  // 11: internship.InternshipService.AddInternship:output_type -> internship.AddInternshipResponse
	4,  // 12: internship.InternshipService.GetInternship:output_type -> internship.GetInternshipResponse
	6,  // 13: internship.InternshipService.GetAllInternships:output_type -> internship.GetAllInternshipsResponse
	8,  // 14: internship.InternshipService.UpdateInternship:output_type -> internship.UpdateInternshipResponse
	10, // 15: internship.InternshipService.DeleteInternship:output_type -> internship.DeleteInternshipResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_proto_internship_internship_proto_init() }
func file_internal_proto_internship_internship_proto_init() {
	if File_internal_proto_internship_internship_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_internship_internship_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternshipFields); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddInternshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddInternshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInternshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInternshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllInternshipsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllInternshipsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInternshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInternshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInternshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_internship_internship_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInternshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_internship_internship_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_internship_internship_proto_goTypes,
		DependencyIndexes: file_internal_proto_internship_internship_proto_depIdxs,
		MessageInfos:      file_internal_proto_internship_internship_proto_msgTypes,
	}.Build()
	File_internal_proto_internship_internship_proto = out.File
	file_internal_proto_internship_internship_proto_rawDesc = nil
	file_internal_proto_internship_internship_proto_goTypes = nil
	file_internal_proto_internship_internship_proto_depIdxs = nil
}
